In [1]:
from tensorflow.keras.preprocessing import image

In [2]:
img = image.load_img('/content/drive/MyDrive/Dataset/1029549.jpg',target_size=(224,224))

In [6]:
img_array = image.img_to_array(img)

In [7]:
img_array

array([[[234., 234., 234.],
        [235., 235., 235.],
        [235., 235., 233.],
        ...,
        [240., 240., 240.],
        [240., 240., 240.],
        [240., 240., 240.]],

       [[234., 234., 234.],
        [235., 235., 235.],
        [235., 235., 235.],
        ...,
        [240., 240., 240.],
        [240., 240., 240.],
        [240., 240., 240.]],

       [[233., 233., 233.],
        [234., 234., 234.],
        [234., 234., 234.],
        ...,
        [240., 240., 240.],
        [240., 240., 240.],
        [238., 238., 238.]],

       ...,

       [[141.,  74.,  31.],
        [138.,  74.,  30.],
        [138.,  74.,  30.],
        ...,
        [154.,  88.,  36.],
        [153.,  90.,  36.],
        [159.,  97.,  38.]],

       [[141.,  74.,  31.],
        [138.,  74.,  30.],
        [138.,  74.,  30.],
        ...,
        [154.,  88.,  36.],
        [153.,  90.,  36.],
        [157.,  95.,  36.]],

       [[142.,  75.,  32.],
        [138.,  74.,  30.],
        [138.,  

In [8]:
img_array.shape

(224, 224, 3)

In [9]:
import numpy as np
expanded_img_array = np.expand_dims(img_array,axis=0)
print(expanded_img_array.shape)

(1, 224, 224, 3)


In [10]:
from tensorflow.keras.applications.resnet50 import ResNet50,preprocess_input
import tensorflow
from tensorflow.keras.preprocessing import image                                     # converting images to arrays, resizing, etc.
from tensorflow.keras.layers import GlobalMaxPooling2D

In [11]:
model = ResNet50(weights='imagenet',include_top=False,input_shape=(224,224,3))
model.trainable = False
model = tensorflow.keras.Sequential([model,GlobalMaxPooling2D()])

94765736/94765736 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [12]:
preprocessed_img = preprocess_input(expanded_img_array)
print(preprocessed_img.shape)
preprocessed_img

(1, 224, 224, 3)


array([[[[130.061, 117.221, 110.32 ],
         [131.061, 118.221, 111.32 ],
         [129.061, 118.221, 111.32 ],
         ...,
         [136.061, 123.221, 116.32 ],
         [136.061, 123.221, 116.32 ],
         [136.061, 123.221, 116.32 ]],

        [[130.061, 117.221, 110.32 ],
         [131.061, 118.221, 111.32 ],
         [131.061, 118.221, 111.32 ],
         ...,
         [136.061, 123.221, 116.32 ],
         [136.061, 123.221, 116.32 ],
         [136.061, 123.221, 116.32 ]],

        [[129.061, 116.221, 109.32 ],
         [130.061, 117.221, 110.32 ],
         [130.061, 117.221, 110.32 ],
         ...,
         [136.061, 123.221, 116.32 ],
         [136.061, 123.221, 116.32 ],
         [134.061, 121.221, 114.32 ]],

        ...,

        [[-72.939, -42.779,  17.32 ],
         [-73.939, -42.779,  14.32 ],
         [-73.939, -42.779,  14.32 ],
         ...,
         [-67.939, -28.779,  30.32 ],
         [-67.939, -26.779,  29.32 ],
         [-65.939, -19.779,  35.32 ]],

        [[

In [13]:
model.predict(preprocessed_img)

1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step


array([[ 1.5425069,  7.658035 ,  6.8010187, ...,  3.0412827, 11.022915 ,
         6.3800945]], dtype=float32)

In [14]:
model.predict(preprocessed_img).flatten()

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 365ms/step


array([ 1.5425069,  7.658035 ,  6.8010187, ...,  3.0412827, 11.022915 ,
        6.3800945], dtype=float32)

In [17]:
model.predict(preprocessed_img).flatten()/norm(model.predict(preprocessed_img).flatten())

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 204ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 231ms/step


array([0.00411579, 0.02043352, 0.01814679, ..., 0.00811489, 0.02941185,
       0.01702366], dtype=float32)

In [16]:
from numpy.linalg import norm
norm(model.predict(preprocessed_img).flatten())

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 369ms/step


np.float32(374.77805)

In [18]:
np.sqrt(np.dot(model.predict(preprocessed_img).flatten(),model.predict(preprocessed_img).flatten()))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 206ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 211ms/step


np.float32(374.77805)